apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: NodePort  
  selector:
    app: influxdb  
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      protocol: TCP