apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: streaming

resources:
- redis-service.yaml
- redis-deployment.yaml


commonLabels:
  scope: redis

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: redis-config
    files:
    - x.conf